name: crdt_sync
description: A dart-native turnkey solution for painless network synchronization
version: 1.0.9
repository: https://github.com/cachapa/crdt_sync

environment:
  sdk: ^3.0.0

dependencies:
  crdt:
    path: ../crdt
  socket_io_client: ^2.0.0

dev_dependencies:
  lints: any
  test: any
  uuid: any